# Generated by Django 3.2.3 on 2021-05-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('ID', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=100)),
                ('LONG', models.FloatField(default=0.0)),
                ('LAT', models.FloatField(default=0.0)),
            ],
        ),
    ]
