# Generated by Django 3.2.3 on 2021-06-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('ID', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('LABEL', models.IntegerField(choices=[(0, 'Binh thuong'), (1, 'Cay nga'), (2, 'Hoa hoan'), (3, 'Ngap lut'), (4, 'Duong xau'), (5, 'Ket xe'), (6, 'Rac thai'), (7, 'Tai nan giao thong')], default=1)),
                ('LONG', models.FloatField(default=0.0)),
                ('LAT', models.FloatField(default=0.0)),
                ('TIME', models.DateTimeField(auto_now_add=True)),
                ('IMAGE', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
